import Ldsec

l = Ldsec.Ldsec()
l.inserirInicio('C')
l.inserirInicio('B')
l.inserirInicio('A')
l.show()
print('_________________________________________________')
#l.inserirFim('E')
#l.show()
#print('_________________________________________________')
#l.removerFim()
#l.show()
#print('_________________________________________________')
#l.removerInicio()
#l.show()
#print('_________________________________________________')
l.inserirAposDet('X','C')
l.show()
print('_________________________________________________')
